Fix README typo
arcticicestudio/nord-highlightjs pull request #9
Opened 2018-01-28 17:40 UTC by controversial

JOSN -> JSON

2018-01-28 19:07 UTC, lukaskollmer commented
Also `your're` -> `you're` in the [Installation](https://github.com/arcticicestudio/nord-highlightjs/blob/develop/README.md#installation) section

2018-01-28 20:37 UTC, arcticicestudio requested changes
Thanks for your contribution :+1: 

Could you please add the change @lukaskollmer mentioned so we can fix both typos in one PR? :smile:

2018-01-29 02:01 UTC, controversial commented
Done

2018-01-29 04:50 UTC, arcticicestudio approved these changes

2018-01-29 04:51 UTC, merged